In [7]:
from sys import argv
from os.path import exists
import json
from pprint import pprint

In [10]:
with open('../inprogress01/static/data/geojson.json') as json_data:
    data = json.load(json_data)
    pprint(data)

{'features': [{'geometry': {'coordinates': [-83.7312291, 42.2681569],
                            'type': 'Point'},
               'properties': {'title': 'Ann Arbor'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-84.3901849, 33.7490987],
                            'type': 'Point'},
               'properties': {'title': 'Atlanta'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-97.7436995, 30.2711286],
                            'type': 'Point'},
               'properties': {'title': 'Austin'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-71.0582912, 42.3602534],
                            'type': 'Point'},
               'properties': {'title': 'Boston'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-80.8431268, 35.2270869],
                            'type': 'Point'},
               'properties': {'title': 'Charlotte'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-87.6244212, 41.8755616],
                            'type': 'Point'},
               'properties': {'title': 'Chicago'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-84.5124602, 39.1014537],
                            'type': 'Point'},
               'properties': {'title': 'Cincinnati'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-81.0343313, 34.0007493],
                            'type': 'Point'},
               'properties': {'title': 'Columbia'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-96.7968559, 32.7762719],
                            'type': 'Point'},
               'properties': {'title': 'Dallas'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-104.9848623, 39.7392364],
                            'type': 'Point'},
               'properties': {'title': 'Denver'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-95.3676974, 29.7589382],
                            'type': 'Point'},
               'properties': {'title': 'Houston'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-81.655651, 30.3321838],
                            'type': 'Point'},
               'properties': {'title': 'Jacksonville'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-118.2427666, 34.0536909],
                            'type': 'Point'},
               'properties': {'title': 'Los Angeles'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-85.759407, 38.2542376],
                            'type': 'Point'},
               'properties': {'title': 'Louisville'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-80.1936589, 25.7742658],
                            'type': 'Point'},
               'properties': {'title': 'Miami'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-93.2654692, 44.9772995],
                            'type': 'Point'},
               'properties': {'title': 'Minneapolis'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-86.7743531, 36.1622296],
                            'type': 'Point'},
               'properties': {'title': 'Nashville'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-74.0060152, 40.7127281],
                            'type': 'Point'},
               'properties': {'title': 'New York'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-76.4321089, 36.9786449],
                            'type': 'Point'},
               'properties': {'title': 'Newport News'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-112.0773456, 33.4485866],
                            'type': 'Point'},
               'properties': {'title': 'Phoenix'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-117.1627714, 32.7174209],
                            'type': 'Point'},
               'properties': {'title': 'San Diego'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-122.4192363, 37.7792808],
                            'type': 'Point'},
               'properties': {'title': 'San Francisco'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-122.3300624, 47.6038321],
                            'type': 'Point'},
               'properties': {'title': 'Seattle'},
               'type': 'Feature'},
              {'geometry': {'coordinates': [-75.9774183, 36.8529841],
                            'type': 'Point'},
               'properties': {'title': 'Virginia Beach'},
               'type': 'Feature'}],
 'type': 'FeatureCollection'}

In [71]:
data['features'][0]['properties']

{'title': 'Ann Arbor'}

In [110]:
keys = data_jobs.keys()

dict_keys(['data scientist', 'data engineer', 'data analyst', 'statistician', 'data & analytics manager'])

In [120]:
# Loops to append job lists to geojson

for f in data['features']:
    city = (f['properties']['title'].lower())
   
    for key in data_jobs:
        value = data_jobs[key]
        f['properties'][key] = (value[city])
        
pprint(data['features'])

[{'geometry': {'coordinates': [-83.7312291, 42.2681569], 'type': 'Point'},
  'properties': {'data & analytics manager': 21,
                 'data analyst': 84,
                 'data engineer': 300,
                 'data scientist': 9,
                 'statistician': 28,
                 'title': 'Ann Arbor'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-84.3901849, 33.7490987], 'type': 'Point'},
  'properties': {'data & analytics manager': 86,
                 'data analyst': 285,
                 'data engineer': 300,
                 'data scientist': 30,
                 'statistician': 66,
                 'title': 'Atlanta'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-97.7436995, 30.2711286], 'type': 'Point'},
  'properties': {'data & analytics manager': 39,
                 'data analyst': 120,
                 'data engineer': 300,
                 'data scientist': None,
                 'statistician': 6,
                 'title': 'Austin'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-71.0582912, 42.3602534], 'type': 'Point'},
  'properties': {'data & analytics manager': 61,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 77,
                 'statistician': 94,
                 'title': 'Boston'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-80.8431268, 35.2270869], 'type': 'Point'},
  'properties': {'data & analytics manager': 42,
                 'data analyst': 252,
                 'data engineer': 300,
                 'data scientist': 6,
                 'statistician': 18,
                 'title': 'Charlotte'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-87.6244212, 41.8755616], 'type': 'Point'},
  'properties': {'data & analytics manager': 119,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 42,
                 'statistician': 149,
                 'title': 'Chicago'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-84.5124602, 39.1014537], 'type': 'Point'},
  'properties': {'data & analytics manager': 15,
                 'data analyst': 95,
                 'data engineer': 201,
                 'data scientist': 15,
                 'statistician': 23,
                 'title': 'Cincinnati'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-81.0343313, 34.0007493], 'type': 'Point'},
  'properties': {'data & analytics manager': 3,
                 'data analyst': 14,
                 'data engineer': 30,
                 'data scientist': 0,
                 'statistician': None,
                 'title': 'Columbia'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-96.7968559, 32.7762719], 'type': 'Point'},
  'properties': {'data & analytics manager': 84,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 15,
                 'statistician': 108,
                 'title': 'Dallas'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-104.9848623, 39.7392364], 'type': 'Point'},
  'properties': {'data & analytics manager': 28,
                 'data analyst': 134,
                 'data engineer': 300,
                 'data scientist': 11,
                 'statistician': 37,
                 'title': 'Denver'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-95.3676974, 29.7589382], 'type': 'Point'},
  'properties': {'data & analytics manager': 41,
                 'data analyst': 231,
                 'data engineer': 300,
                 'data scientist': 12,
                 'statistician': 79,
                 'title': 'Houston'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-81.655651, 30.3321838], 'type': 'Point'},
  'properties': {'data & analytics manager': 11,
                 'data analyst': 84,
                 'data engineer': 194,
                 'data scientist': 0,
                 'statistician': 12,
                 'title': 'Jacksonville'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-118.2427666, 34.0536909], 'type': 'Point'},
  'properties': {'data & analytics manager': 97,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 95,
                 'statistician': 148,
                 'title': 'Los Angeles'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-85.759407, 38.2542376], 'type': 'Point'},
  'properties': {'data & analytics manager': 6,
                 'data analyst': 31,
                 'data engineer': 107,
                 'data scientist': 2,
                 'statistician': 6,
                 'title': 'Louisville'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-80.1936589, 25.7742658], 'type': 'Point'},
  'properties': {'data & analytics manager': 23,
                 'data analyst': 143,
                 'data engineer': 239,
                 'data scientist': 9,
                 'statistician': 50,
                 'title': 'Miami'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-93.2654692, 44.9772995], 'type': 'Point'},
  'properties': {'data & analytics manager': 19,
                 'data analyst': 252,
                 'data engineer': 300,
                 'data scientist': 11,
                 'statistician': 57,
                 'title': 'Minneapolis'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-86.7743531, 36.1622296], 'type': 'Point'},
  'properties': {'data & analytics manager': 13,
                 'data analyst': 125,
                 'data engineer': 148,
                 'data scientist': 4,
                 'statistician': 30,
                 'title': 'Nashville'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-74.0060152, 40.7127281], 'type': 'Point'},
  'properties': {'data & analytics manager': 160,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 94,
                 'statistician': 168,
                 'title': 'New York'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-76.4321089, 36.9786449], 'type': 'Point'},
  'properties': {'data & analytics manager': 13,
                 'data analyst': 45,
                 'data engineer': 82,
                 'data scientist': None,
                 'statistician': 8,
                 'title': 'Newport News'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-112.0773456, 33.4485866], 'type': 'Point'},
  'properties': {'data & analytics manager': 32,
                 'data analyst': 123,
                 'data engineer': 275,
                 'data scientist': 8,
                 'statistician': 26,
                 'title': 'Phoenix'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-117.1627714, 32.7174209], 'type': 'Point'},
  'properties': {'data & analytics manager': 15,
                 'data analyst': 96,
                 'data engineer': 241,
                 'data scientist': 24,
                 'statistician': 23,
                 'title': 'San Diego'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-122.4192363, 37.7792808], 'type': 'Point'},
  'properties': {'data & analytics manager': 85,
                 'data analyst': 300,
                 'data engineer': 300,
                 'data scientist': 89,
                 'statistician': 91,
                 'title': 'San Francisco'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-122.3300624, 47.6038321], 'type': 'Point'},
  'properties': {'data & analytics manager': 32,
                 'data analyst': 91,
                 'data engineer': 300,
                 'data scientist': 12,
                 'statistician': 31,
                 'title': 'Seattle'},
  'type': 'Feature'},
 {'geometry': {'coordinates': [-75.9774183, 36.8529841], 'type': 'Point'},
  'properties': {'data & analytics manager': 13,
                 'data analyst': 45,
                 'data engineer': 81,
                 'data scientist': None,
                 'statistician': 8,
                 'title': 'Virginia Beach'},
  'type': 'Feature'}]

In [ ]:
# Turn dictionary into JSON file
with open('city_jobs.geojson', 'w') as fp:
    json.dump(data, fp)

In [73]:
for key, value in data.items():
    print(key, value)

type FeatureCollection
features [{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-83.7312291, 42.2681569]}, 'properties': {'title': 'Ann Arbor'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-84.3901849, 33.7490987]}, 'properties': {'title': 'Atlanta'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-97.7436995, 30.2711286]}, 'properties': {'title': 'Austin'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-71.0582912, 42.3602534]}, 'properties': {'title': 'Boston'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-80.8431268, 35.2270869]}, 'properties': {'title': 'Charlotte'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-87.6244212, 41.8755616]}, 'properties': {'title': 'Chicago'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-84.5124602, 39.1014537]}, 'properties': {'title': 'Cincinnati'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-81.0343313, 34.0007493]}, 'properties': {'title': 'Columbia'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-96.7968559, 32.7762719]}, 'properties': {'title': 'Dallas'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-104.9848623, 39.7392364]}, 'properties': {'title': 'Denver'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-95.3676974, 29.7589382]}, 'properties': {'title': 'Houston'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-81.655651, 30.3321838]}, 'properties': {'title': 'Jacksonville'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-118.2427666, 34.0536909]}, 'properties': {'title': 'Los Angeles'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-85.759407, 38.2542376]}, 'properties': {'title': 'Louisville'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-80.1936589, 25.7742658]}, 'properties': {'title': 'Miami'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-93.2654692, 44.9772995]}, 'properties': {'title': 'Minneapolis'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-86.7743531, 36.1622296]}, 'properties': {'title': 'Nashville'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-74.0060152, 40.7127281]}, 'properties': {'title': 'New York'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-76.4321089, 36.9786449]}, 'properties': {'title': 'Newport News'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-112.0773456, 33.4485866]}, 'properties': {'title': 'Phoenix'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-117.1627714, 32.7174209]}, 'properties': {'title': 'San Diego'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-122.4192363, 37.7792808]}, 'properties': {'title': 'San Francisco'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-122.3300624, 47.6038321]}, 'properties': {'title': 'Seattle'}}, {'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [-75.9774183, 36.8529841]}, 'properties': {'title': 'Virginia Beach'}}]

In [34]:
with open('job_counts.json') as json_data:
    data_jobs = json.load(json_data)
    pprint(data_jobs)

{'data & analytics manager': {'ann arbor': 21,
                              'atlanta': 86,
                              'austin': 39,
                              'boston': 61,
                              'charlotte': 42,
                              'chicago': 119,
                              'cincinnati': 15,
                              'columbia': 3,
                              'dallas': 84,
                              'denver': 28,
                              'houston': 41,
                              'jacksonville': 11,
                              'los angeles': 97,
                              'louisville': 6,
                              'miami': 23,
                              'minneapolis': 19,
                              'nashville': 13,
                              'new york': 160,
                              'newport news': 13,
                              'phoenix': 32,
                              'san diego': 15,
                              'san francisco': 85,
                              'seattle': 32,
                              'virginia beach': 13},
 'data analyst': {'ann arbor': 84,
                  'atlanta': 285,
                  'austin': 120,
                  'boston': 300,
                  'charlotte': 252,
                  'chicago': 300,
                  'cincinnati': 95,
                  'columbia': 14,
                  'dallas': 300,
                  'denver': 134,
                  'houston': 231,
                  'jacksonville': 84,
                  'los angeles': 300,
                  'louisville': 31,
                  'miami': 143,
                  'minneapolis': 252,
                  'nashville': 125,
                  'new york': 300,
                  'newport news': 45,
                  'phoenix': 123,
                  'san diego': 96,
                  'san francisco': 300,
                  'seattle': 91,
                  'virginia beach': 45},
 'data engineer': {'ann arbor': 300,
                   'atlanta': 300,
                   'austin': 300,
                   'boston': 300,
                   'charlotte': 300,
                   'chicago': 300,
                   'cincinnati': 201,
                   'columbia': 30,
                   'dallas': 300,
                   'denver': 300,
                   'houston': 300,
                   'jacksonville': 194,
                   'los angeles': 300,
                   'louisville': 107,
                   'miami': 239,
                   'minneapolis': 300,
                   'nashville': 148,
                   'new york': 300,
                   'newport news': 82,
                   'phoenix': 275,
                   'san diego': 241,
                   'san francisco': 300,
                   'seattle': 300,
                   'virginia beach': 81},
 'data scientist': {'ann arbor': 9,
                    'atlanta': 30,
                    'austin': None,
                    'boston': 77,
                    'charlotte': 6,
                    'chicago': 42,
                    'cincinnati': 15,
                    'columbia': 0,
                    'dallas': 15,
                    'denver': 11,
                    'houston': 12,
                    'jacksonville': 0,
                    'los angeles': 95,
                    'louisville': 2,
                    'miami': 9,
                    'minneapolis': 11,
                    'nashville': 4,
                    'new york': 94,
                    'newport news': None,
                    'phoenix': 8,
                    'san diego': 24,
                    'san francisco': 89,
                    'seattle': 12,
                    'virginia beach': None},
 'statistician': {'ann arbor': 28,
                  'atlanta': 66,
                  'austin': 6,
                  'boston': 94,
                  'charlotte': 18,
                  'chicago': 149,
                  'cincinnati': 23,
                  'columbia': None,
                  'dallas': 108,
                  'denver': 37,
                  'houston': 79,
                  'jacksonville': 12,
                  'los angeles': 148,
                  'louisville': 6,
                  'miami': 50,
                  'minneapolis': 57,
                  'nashville': 30,
                  'new york': 168,
                  'newport news': 8,
                  'phoenix': 26,
                  'san diego': 23,
                  'san francisco': 91,
                  'seattle': 31,
                  'virginia beach': 8}}

In [59]:
data_jobs['Data Scientist'.lower()]

{'ann arbor': 9,
 'atlanta': 30,
 'austin': None,
 'boston': 77,
 'charlotte': 6,
 'chicago': 42,
 'cincinnati': 15,
 'columbia': 0,
 'dallas': 15,
 'denver': 11,
 'houston': 12,
 'jacksonville': 0,
 'los angeles': 95,
 'louisville': 2,
 'miami': 9,
 'minneapolis': 11,
 'nashville': 4,
 'new york': 94,
 'newport news': None,
 'phoenix': 8,
 'san diego': 24,
 'san francisco': 89,
 'seattle': 12,
 'virginia beach': None}

In [35]:
data_jobs.keys()

dict_keys(['data scientist', 'data engineer', 'data analyst', 'statistician', 'data & analytics manager'])

In [37]:
ds = data_jobs['data scientist']

In [43]:
for d in ds:
    print(d)

ann arbor
atlanta
austin
boston
charlotte
chicago
cincinnati
columbia
dallas
denver
houston
jacksonville
los angeles
louisville
miami
minneapolis
nashville
new york
newport news
phoenix
san diego
san francisco
seattle
virginia beach